var dir_a8d8e59947adb18b6db2afc7a0c714ad =
[
    [ "cholesky_decompose.hpp", "d2/daf/rev_2mat_2fun_2cholesky__decompose_8hpp.html", "d2/daf/rev_2mat_2fun_2cholesky__decompose_8hpp" ],
    [ "columns_dot_product.hpp", "dd/d54/rev_2mat_2fun_2columns__dot__product_8hpp.html", "dd/d54/rev_2mat_2fun_2columns__dot__product_8hpp" ],
    [ "columns_dot_self.hpp", "d5/d3d/rev_2mat_2fun_2columns__dot__self_8hpp.html", "d5/d3d/rev_2mat_2fun_2columns__dot__self_8hpp" ],
    [ "cov_exp_quad.hpp", "d3/d31/rev_2mat_2fun_2cov__exp__quad_8hpp.html", "d3/d31/rev_2mat_2fun_2cov__exp__quad_8hpp" ],
    [ "crossprod.hpp", "dd/d1d/rev_2mat_2fun_2crossprod_8hpp.html", "dd/d1d/rev_2mat_2fun_2crossprod_8hpp" ],
    [ "determinant.hpp", "d7/d14/rev_2mat_2fun_2determinant_8hpp.html", "d7/d14/rev_2mat_2fun_2determinant_8hpp" ],
    [ "divide.hpp", "d4/dba/rev_2mat_2fun_2divide_8hpp.html", "d4/dba/rev_2mat_2fun_2divide_8hpp" ],
    [ "dot_product.hpp", "d8/d40/rev_2mat_2fun_2dot__product_8hpp.html", "d8/d40/rev_2mat_2fun_2dot__product_8hpp" ],
    [ "dot_self.hpp", "da/da9/rev_2mat_2fun_2dot__self_8hpp.html", "da/da9/rev_2mat_2fun_2dot__self_8hpp" ],
    [ "Eigen_NumTraits.hpp", "d8/d9e/rev_2mat_2fun_2_eigen___num_traits_8hpp.html", null ],
    [ "gp_exp_quad_cov.hpp", "dc/d00/rev_2mat_2fun_2gp__exp__quad__cov_8hpp.html", "dc/d00/rev_2mat_2fun_2gp__exp__quad__cov_8hpp" ],
    [ "gp_periodic_cov.hpp", "d9/d63/rev_2mat_2fun_2gp__periodic__cov_8hpp.html", "d9/d63/rev_2mat_2fun_2gp__periodic__cov_8hpp" ],
    [ "grad.hpp", "db/d54/mat_2fun_2grad_8hpp.html", "db/d54/mat_2fun_2grad_8hpp" ],
    [ "initialize_variable.hpp", "d0/dd3/initialize__variable_8hpp.html", "d0/dd3/initialize__variable_8hpp" ],
    [ "inverse.hpp", "db/dbf/rev_2mat_2fun_2inverse_8hpp.html", "db/dbf/rev_2mat_2fun_2inverse_8hpp" ],
    [ "LDLT_alloc.hpp", "db/d3b/_l_d_l_t__alloc_8hpp.html", [
      [ "LDLT_alloc", "d3/d3f/classstan_1_1math_1_1_l_d_l_t__alloc.html", "d3/d3f/classstan_1_1math_1_1_l_d_l_t__alloc" ]
    ] ],
    [ "LDLT_factor.hpp", "d1/ddd/rev_2mat_2fun_2_l_d_l_t__factor_8hpp.html", [
      [ "LDLT_factor< var, R, C >", "d7/d6e/classstan_1_1math_1_1_l_d_l_t__factor_3_01var_00_01_r_00_01_c_01_4.html", "d7/d6e/classstan_1_1math_1_1_l_d_l_t__factor_3_01var_00_01_r_00_01_c_01_4" ]
    ] ],
    [ "log_determinant.hpp", "d6/d97/rev_2mat_2fun_2log__determinant_8hpp.html", "d6/d97/rev_2mat_2fun_2log__determinant_8hpp" ],
    [ "log_determinant_ldlt.hpp", "d0/ddc/rev_2mat_2fun_2log__determinant__ldlt_8hpp.html", "d0/ddc/rev_2mat_2fun_2log__determinant__ldlt_8hpp" ],
    [ "log_determinant_spd.hpp", "d3/d36/rev_2mat_2fun_2log__determinant__spd_8hpp.html", "d3/d36/rev_2mat_2fun_2log__determinant__spd_8hpp" ],
    [ "log_softmax.hpp", "d1/d1c/rev_2mat_2fun_2log__softmax_8hpp.html", "d1/d1c/rev_2mat_2fun_2log__softmax_8hpp" ],
    [ "log_sum_exp.hpp", "d0/d6a/rev_2mat_2fun_2log__sum__exp_8hpp.html", "d0/d6a/rev_2mat_2fun_2log__sum__exp_8hpp" ],
    [ "matrix_exp_multiply.hpp", "df/dea/rev_2mat_2fun_2matrix__exp__multiply_8hpp.html", "df/dea/rev_2mat_2fun_2matrix__exp__multiply_8hpp" ],
    [ "matrix_power.hpp", "d4/d53/rev_2mat_2fun_2matrix__power_8hpp.html", "d4/d53/rev_2mat_2fun_2matrix__power_8hpp" ],
    [ "mdivide_left.hpp", "dd/d9f/rev_2mat_2fun_2mdivide__left_8hpp.html", "dd/d9f/rev_2mat_2fun_2mdivide__left_8hpp" ],
    [ "mdivide_left_ldlt.hpp", "d5/d05/rev_2mat_2fun_2mdivide__left__ldlt_8hpp.html", "d5/d05/rev_2mat_2fun_2mdivide__left__ldlt_8hpp" ],
    [ "mdivide_left_spd.hpp", "da/d27/rev_2mat_2fun_2mdivide__left__spd_8hpp.html", "da/d27/rev_2mat_2fun_2mdivide__left__spd_8hpp" ],
    [ "mdivide_left_tri.hpp", "de/d89/rev_2mat_2fun_2mdivide__left__tri_8hpp.html", "de/d89/rev_2mat_2fun_2mdivide__left__tri_8hpp" ],
    [ "multiply.hpp", "da/de9/rev_2mat_2fun_2multiply_8hpp.html", "da/de9/rev_2mat_2fun_2multiply_8hpp" ],
    [ "multiply_lower_tri_self_transpose.hpp", "d3/d4a/rev_2mat_2fun_2multiply__lower__tri__self__transpose_8hpp.html", "d3/d4a/rev_2mat_2fun_2multiply__lower__tri__self__transpose_8hpp" ],
    [ "ordered_constrain.hpp", "d7/df8/rev_2mat_2fun_2ordered__constrain_8hpp.html", "d7/df8/rev_2mat_2fun_2ordered__constrain_8hpp" ],
    [ "positive_ordered_constrain.hpp", "d9/db2/rev_2mat_2fun_2positive__ordered__constrain_8hpp.html", "d9/db2/rev_2mat_2fun_2positive__ordered__constrain_8hpp" ],
    [ "quad_form.hpp", "d7/d62/rev_2mat_2fun_2quad__form_8hpp.html", "d7/d62/rev_2mat_2fun_2quad__form_8hpp" ],
    [ "quad_form_sym.hpp", "dd/d6c/rev_2mat_2fun_2quad__form__sym_8hpp.html", "dd/d6c/rev_2mat_2fun_2quad__form__sym_8hpp" ],
    [ "rows_dot_product.hpp", "dc/db6/rev_2mat_2fun_2rows__dot__product_8hpp.html", "dc/db6/rev_2mat_2fun_2rows__dot__product_8hpp" ],
    [ "sd.hpp", "dc/dd1/rev_2mat_2fun_2sd_8hpp.html", "dc/dd1/rev_2mat_2fun_2sd_8hpp" ],
    [ "simplex_constrain.hpp", "db/d0e/rev_2mat_2fun_2simplex__constrain_8hpp.html", "db/d0e/rev_2mat_2fun_2simplex__constrain_8hpp" ],
    [ "softmax.hpp", "d1/d4c/rev_2mat_2fun_2softmax_8hpp.html", "d1/d4c/rev_2mat_2fun_2softmax_8hpp" ],
    [ "squared_distance.hpp", "d6/d88/rev_2mat_2fun_2squared__distance_8hpp.html", "d6/d88/rev_2mat_2fun_2squared__distance_8hpp" ],
    [ "stan_print.hpp", "d3/d9b/rev_2mat_2fun_2stan__print_8hpp.html", "d3/d9b/rev_2mat_2fun_2stan__print_8hpp" ],
    [ "sum.hpp", "d4/da2/rev_2mat_2fun_2sum_8hpp.html", "d4/da2/rev_2mat_2fun_2sum_8hpp" ],
    [ "tcrossprod.hpp", "d1/d17/rev_2mat_2fun_2tcrossprod_8hpp.html", "d1/d17/rev_2mat_2fun_2tcrossprod_8hpp" ],
    [ "to_var.hpp", "d1/dde/mat_2fun_2to__var_8hpp.html", "d1/dde/mat_2fun_2to__var_8hpp" ],
    [ "trace_gen_inv_quad_form_ldlt.hpp", "d0/d10/rev_2mat_2fun_2trace__gen__inv__quad__form__ldlt_8hpp.html", "d0/d10/rev_2mat_2fun_2trace__gen__inv__quad__form__ldlt_8hpp" ],
    [ "trace_gen_quad_form.hpp", "da/d19/rev_2mat_2fun_2trace__gen__quad__form_8hpp.html", "da/d19/rev_2mat_2fun_2trace__gen__quad__form_8hpp" ],
    [ "trace_inv_quad_form_ldlt.hpp", "da/d64/rev_2mat_2fun_2trace__inv__quad__form__ldlt_8hpp.html", "da/d64/rev_2mat_2fun_2trace__inv__quad__form__ldlt_8hpp" ],
    [ "trace_quad_form.hpp", "d3/de2/rev_2mat_2fun_2trace__quad__form_8hpp.html", "d3/de2/rev_2mat_2fun_2trace__quad__form_8hpp" ],
    [ "typedefs.hpp", "d8/d9f/rev_2mat_2fun_2typedefs_8hpp.html", "d8/d9f/rev_2mat_2fun_2typedefs_8hpp" ],
    [ "unit_vector_constrain.hpp", "d6/dc5/rev_2mat_2fun_2unit__vector__constrain_8hpp.html", "d6/dc5/rev_2mat_2fun_2unit__vector__constrain_8hpp" ],
    [ "variance.hpp", "d9/d63/rev_2mat_2fun_2variance_8hpp.html", "d9/d63/rev_2mat_2fun_2variance_8hpp" ]
];